# RNA-seq workflow configuration

# Path to metasheet with sample information
metasheet_path: "resources/metadata/samples.csv"

# Test mode flag - will be overridden by command line when needed
test_mode: false

# Resource parameters
fastqc_threads: 2
fastqc_memory: 4000
multiqc_memory: 4000
trimming_threads: 4
trimming_memory: 32000
star_threads: 8
star_memory: 32000
star_index_threads: 16
star_index_memory: 40000
bam_index_memory: 4000
metrics_memory: 4000
multiqc_alignment_memory: 4000
featurecounts_threads: 4
featurecounts_memory: 8000
merge_counts_memory: 4000
multiqc_counts_memory: 4000

# Reference files
genome_fasta: "resources/genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
gtf_file: "resources/genome/Homo_sapiens.GRCh38.90.gtf"
star_index: "resources/genome/star_index"

# STAR parameters
sjdb_overhang: 100            # Read length - 1
star_mismatch: 10             # Max mismatches
star_multimap: 20             # Max multimappers
star_score_min: 0.66          # Min alignment score
star_match_min: 0.66          # Min match length
star_sjdb_overhang_min: 3     # Min splice junction overhang
star_intron_max: 500000       # Max intron length

# Default trimming parameters (will be overridden by auto-detection)
leading_quality: 3
trailing_quality: 3
sliding_window: "4:15"
min_length: 36

# Feature counts parameters
feature_type: "exon"          # Feature type to count (exon, gene, transcript)
attribute: "gene_id"          # Attribute to use for grouping features
strand_specificity: "0"       # Strand specificity: 0 (unstranded), 1 (stranded), 2 (reversely stranded)
featurecounts_extra: "-p -B -C --fracOverlap 0.2"  # Additional parameters for featureCounts